name: release-drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  create_release_draft:
    permissions:
      contents: write
      pull-requests: write
    name: Create Release Draft
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PIPELINE }}